version: "3.7"
services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: gochattyuser
      POSTGRES_PASSWORD: gochattypass
      POSTGRES_DB: gochattydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./scripts/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql:ro

  rabbitmq:
    image: rabbitmq:3.11-management
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always

  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    restart: always
    environment:
      DATABASE_URL: postgres://gochattyuser:gochattypass@db:5432/gochattydb?sslmode=disable
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
    ports:
      - "8080:8080"
    depends_on:
      - db
      - rabbitmq

volumes:
  pgdata:
